title: Pre-Bootcamp-Prep
description: >-
  This is curriculum for being best prepared before beginning a Web Development
  Bootcamp.
steps:
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
